Intent: The intent of the source code seems to be a helper function that checks if there is an exception handler in a given node. The test case 'testIssue794b' is designed to test if the function correctly handles multiple try-catch blocks in a JavaScript code, and whether it can handle a function call (someFunction) within these blocks.

Fix strategy: The test case is failing because the 'hasExceptionHandler' function is hardcoded to always return false. This does not fulfill its purpose of checking for an exception handler in a given node. To fix this issue, the 'hasExceptionHandler' function needs to be implemented such that it checks if the node has an exception handler and returns true if it does, and false otherwise. This could be done by parsing through the node and checking for 'catch' statements. If a 'catch' statement is found, the function should return true. If no 'catch' statements are found after going through all the code in the node, then it should return false.